export const PICARAIL_PART_ID = "picarail";

export const PICA_TILE_PITCH = 10;
export const PICA_TILE_SLOT_WIDTH = 6.03;
export const PICA_SLOT_DEPTH = 3.0;

export const PICA_RAIL_BASE_WIDTH = 15.67;
export const PICA_RAIL_TOP_WIDTH = 20.6343145750508;
export const PICA_RAIL_TOP_FLAT_WIDTH = PICA_RAIL_BASE_WIDTH;
export const PICA_RAIL_HEIGHT = 9.32;
export const PICA_RAIL_BODY_HEIGHT = 3.79;
export const PICA_RAIL_LOWER_SHOULDER_HEIGHT = 6.27215728752538;
export const PICA_RAIL_UPPER_SHOULDER_HEIGHT = 6.83784271247462;
export const PICA_RAIL_SHOULDER_HEIGHT = 6.555;
export const PICA_RAIL_TILE_REAR_HEIGHT = 3.0;

export const PICA_TILE_OFFSET = (PICA_TILE_PITCH - PICA_TILE_SLOT_WIDTH) / 2;

export const PICA_SCREW_HOLE_RADIUS = 5.7;
export const PICA_SCREW_HOLE_CONE_BOTTOM_RADIUS = 6.3;
export const PICA_SCREW_HOLE_HEAD_RADIUS = 7.1;
export const PICA_SCREW_HOLE_CONE_BOTTOM_Z = 2.72;
export const PICA_SCREW_HOLE_CONE_TOP_Z = 3.52;
export const PICA_SCREW_HOLE_SEGMENTS_DEFAULT = 128;
export const PICA_SCREW_HOLE_SEGMENTS_MIN = 12;
export const PICA_SCREW_HOLE_SEGMENTS_MAX = 360;

export const PICA_OPEN_GRID_TILE_SIZE_MIN = 1;
export const PICA_OPEN_GRID_TILE_SIZE_MAX = 500;
export const PICA_OPEN_GRID_LENGTH_MIN = 1;
export const PICA_OPEN_GRID_LENGTH_MAX = 200;

export const PICA_OPEN_GRID_TILE_SIZE_DEFAULT = 28;
export const PICA_OPEN_GRID_TILE_LENGTH_DEFAULT = 2;
export const PICA_OPEN_GRID_LENGTH_DEFAULT = PICA_OPEN_GRID_TILE_LENGTH_DEFAULT;
