export const PICARAIL_PART_ID = "picarail";

export const PICA_TILE_PITCH = 10;
export const PICA_TILE_SLOT_WIDTH = 5.23;
export const PICA_SLOT_DEPTH = 3.0;

export const PICA_RAIL_BASE_WIDTH = 15.67;
export const PICA_RAIL_TOP_WIDTH = 21.2;
export const PICA_RAIL_TOP_FLAT_WIDTH = PICA_RAIL_BASE_WIDTH;
export const PICA_RAIL_HEIGHT = 9.32;
export const PICA_RAIL_BODY_HEIGHT =
	PICA_RAIL_HEIGHT - (PICA_RAIL_TOP_WIDTH - PICA_RAIL_BASE_WIDTH);
export const PICA_RAIL_SHOULDER_HEIGHT =
	PICA_RAIL_BODY_HEIGHT + (PICA_RAIL_TOP_WIDTH - PICA_RAIL_BASE_WIDTH) / 2;
export const PICA_RAIL_TILE_REAR_HEIGHT = 3.0;

export const PICA_TILE_OFFSET = (PICA_TILE_PITCH - PICA_TILE_SLOT_WIDTH) / 2;

export const PICA_OPEN_GRID_TILE_SIZE_MIN = 1;
export const PICA_OPEN_GRID_TILE_SIZE_MAX = 500;
export const PICA_OPEN_GRID_LENGTH_MIN = 1;
export const PICA_OPEN_GRID_LENGTH_MAX = 200;

export const PICA_OPEN_GRID_TILE_SIZE_DEFAULT = 28;
export const PICA_OPEN_GRID_TILE_LENGTH_DEFAULT = 2;
export const PICA_OPEN_GRID_LENGTH_DEFAULT = PICA_OPEN_GRID_TILE_LENGTH_DEFAULT;
